"use client";

import { useState } from "react";
import { DotLottieReact } from "@lottiefiles/dotlottie-react";
import { motion, useReducedMotion } from "framer-motion";
import { CheckCircle2 } from "lucide-react";
import { Button } from "../ui/button";
import { formatNumber } from "../lib/format";

export interface IndexCelebrationProps {
  repoName: string;
  /** Pages generated by the first index, when known. */
  pagesGenerated?: number;
  /** Owl Lottie asset path, served from the consuming app's public/. */
  lottieSrc?: string;
  /** "Start here" handoff content, e.g. a FirstFiveFiles card. */
  children?: React.ReactNode;
  exploreLabel?: string;
  onExplore?: () => void;
}

const CONFETTI_COLORS = [
  "var(--color-accent-primary)",
  "var(--color-fresh)",
  "var(--color-warning)",
  "var(--color-stale)",
];

/**
 * First-index success moment: the brand owl takes a bow over a confetti
 * burst, then hands off to "start here" content. Falls back to a plain
 * check icon if the animation asset fails, and skips the confetti when the
 * user prefers reduced motion.
 */
export function IndexCelebration({
  repoName,
  pagesGenerated,
  lottieSrc = "/owl-loading.json",
  children,
  exploreLabel = "Explore the dashboard",
  onExplore,
}: IndexCelebrationProps) {
  const reducedMotion = useReducedMotion();
  const [lottieFailed, setLottieFailed] = useState(false);

  return (
    <div className="relative overflow-hidden rounded-lg border border-[var(--color-border-default)] p-8 text-center [background-image:var(--gradient-warm-wash)]">
      {!reducedMotion && (
        <div aria-hidden className="pointer-events-none absolute inset-0">
          {Array.from({ length: 16 }).map((_, i) => (
            <motion.span
              key={i}
              className="absolute top-1/3 left-1/2 h-2 w-1.5 rounded-sm"
              style={{ backgroundColor: CONFETTI_COLORS[i % CONFETTI_COLORS.length] }}
              initial={{ x: 0, y: 0, opacity: 1, rotate: 0 }}
              animate={{
                x: (i - 7.5) * 28 + ((i * 37) % 23) - 11,
                y: 140 + ((i * 53) % 60),
                opacity: 0,
                rotate: i % 2 === 0 ? 260 : -220,
              }}
              transition={{ duration: 1.6 + (i % 5) * 0.18, ease: "easeOut" }}
            />
          ))}
        </div>
      )}

      <div className="relative flex flex-col items-center gap-3">
        {lottieFailed ? (
          <CheckCircle2 className="h-14 w-14 text-[var(--color-fresh)]" />
        ) : (
          <DotLottieReact
            src={lottieSrc}
            autoplay
            loop={false}
            style={{ width: 120, height: 120 }}
            dotLottieRefCallback={(dotLottie) => {
              dotLottie?.addEventListener("loadError", () => setLottieFailed(true));
            }}
          />
        )}
        <div className="space-y-1">
          <h3 className="text-lg font-semibold text-[var(--color-text-primary)]">
            {repoName} is ready
          </h3>
          <p className="text-sm text-[var(--color-text-secondary)]">
            {pagesGenerated != null && pagesGenerated > 0
              ? `${formatNumber(pagesGenerated)} documentation pages generated. `
              : "The index is built. "}
            Search, health, and architecture views are live.
          </p>
        </div>
        {onExplore && (
          <Button size="sm" onClick={onExplore}>
            {exploreLabel}
          </Button>
        )}
      </div>

      {children && <div className="relative mt-6 text-left">{children}</div>}
    </div>
  );
}
